[project]
name = "aspen-vpn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.5",
    "python-wireguard>=0.2.2",
    "requests>=2.32.3",
]
